# ~/.tmuxinator/base.yml

name: base
root: ~/src/getty/unisporkal

windows:
  - cns:
      layout: main-vertical
      panes:
        - nvim:
            - nvim
  - term:
      layout: main-vertical
      panes:
        - term:
